version: '3.1'

services:
  db:
    image: mongo:3.6.7-jessie
    networks:
      - db-be_network
  be:
    build: ./backend
    depends_on:
      - db
    secrets:
      - jwt.key
    networks:
      - db-be_network
      - nginx-be_network
  fe:
    build: ./frontend
    depends_on:
      - be
    volumes:
      - fe_statics:/opt/app
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - fe
      - be
    secrets:
      - site.key
      - site.crt
      - dhparam.pem
    networks:
      - nginx-be_network
    volumes:
      - fe_statics:/opt/app/fe

networks:
  db-be_network:
    driver: bridge
  nginx-be_network:
    driver: bridge

volumes:
  fe_statics:

secrets:
  site.key:
    file: secrets/siteCertificate/site.key
  site.crt:
    file: secrets/siteCertificate/site.crt
  dhparam.pem:
    file: secrets/siteCertificate/dhparam.pem
  jwt.key:
    file: secrets/jwt.key
