version: '3.1'

services:
  db:
    image: mongo:3.4
    command: ["mongod", "--smallfiles", "--nojournal"]
    networks:
      - db-be_network
  be:
    build: ./backend
    depends_on:
      - db
    networks:
      - db-be_network
      - nginx-be_network
  fe:
    build: ./frontend
    depends_on:
      - be
    volumes:
      - fe_statics:/opt/app/dist
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - fe
      - be
    secrets:
      - site.key
      - site.crt
    networks:
      - nginx-be_network
    volumes:
      - fe_statics:/opt/app/dist

networks:
  db-be_network:
    driver: bridge
  nginx-be_network:
    driver: bridge

volumes:
  fe_statics:

secrets:
  site.key:
    file: secrets/site.key
  site.crt:
    file: secrets/site.crt
