version: '3'

services:
  db:
    image: mongo:3.4
    command: ["mongod", "--smallfiles", "--nojournal"]
    networks:
      - node_network
  be:
    build: ./backend
    ports:
      - "7778:7778"
    depends_on:
      - db
    volumes:
      - ./backend:/opt/app
    networks:
      - node_network
  fe:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    depends_on:
      - be
    volumes:
      - ./frontend:/opt/app

networks:
  node_network:
    driver: bridge
